### ISSUE TITLE
Input type copied incorrectly

### ISSUE THREAD

**Issue by kristoferjoseph** [yoshuawuyts/nanomorph#12]
Heyo!
I have a failing test for copying over an input type:
https://github.com/kristoferjoseph/nanomorph/blob/master/test.js#L45

I made sure that this isn't an issue with `bel` already.

**Comment by kristoferjoseph** [comment]
OK I was wrong! Turns out this was a bug in raynos/global/min-document which is a dependency of bel. It only happens when the code is not run in the browser which is why the bel tests were passing and not here. 

I chased it down and got PRs opened for the fixes will PR here once bel merges.

**Comment by yoshuawuyts** [comment]
Sweet, thanks for chasing it down! :D
