### ISSUE TITLE
idea: abstract-dom-morph

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/nanomorph#14]
If this library becomes a thing we would probably want to keep parity with the `nanomorph` diffing algorithm or (`yo-yo` if they're not keen). It would be cool if we could create a shared testing library that defines all behavior we expect from a diffing library so we can make sure our implementations adhere to this. I would imagine the API would be along the lines of:

``` js
const abstract = require('abstract-dom-morph/test')
const nanomorph = require('nanomorph')

abstract(nanomorph)
```

This could help with a possible migration of `choo` to a tinier diffing implementation and help foster the creation of new DOM-only diffing algorithms. Thoughts?

cc/ @kristoferjoseph 
### See Also
- https://github.com/maxogden/abstract-blob-store/
- https://github.com/mafintosh/abstract-chunk-store/
- https://github.com/juliangruber/abstract-random-access/

**Comment by kristoferjoseph** [comment]
That is a great idea! 
I actually looked at porting the  morphdom tests here using the same line of thinking. Unfortunately the tests are too specific to the morphdom implementation. 

In general it seems like a really useful approach to have an abstract to outline the general expectations of a library and how to test it.  👍💯
