### ISSUE TITLE
annotate source code

### ISSUE THREAD

**Issue by stevemao** [yoshuawuyts/nanomorph#2]
Hi
Do you think it's a good idea to annotate the source for educational purposes? Just like how [the-super-tiny-compiler](https://github.com/thejameskyle/the-super-tiny-compiler) does. I really like the idea of a tiny module demonstrating hot but hard technologies. If not this module maybe you could make another one for educational purposes. It would also reduce the barrier of contributing your choo module I believe. Thanks!

**Comment by yoshuawuyts** [comment]
Hah, so right now it's a fork of `morphdom` so I'm not 100% sure what's going on right now either; but it's def worth a try I think. Nice idea!

**Comment by yoshuawuyts** [comment]
Heya, how's this? https://github.com/yoshuawuyts/nanomorph/blob/master/index.js#L6-L18

**Comment by stevemao** [comment]
LGTM :) cheers!
