### ISSUE TITLE
Add isSameNode check.

### ISSUE THREAD

**Issue by kristoferjoseph** [yoshuawuyts/nanomorph#20]

**Comment by yoshuawuyts** [comment]
perfect, yeah we need this - should be straight forward to implement I reckon

- spec https://developer.mozilla.org/en/docs/Web/API/Node/isSameNode
- code in morphdom https://github.com/patrick-steele-idem/morphdom/search?utf8=%E2%9C%93&q=issamenode

**Comment by kristoferjoseph** [comment]
on it.
