### ISSUE TITLE
rename update-dom

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/nanomorph#21]
right now the update-dom file allows creating an update loop from a single element that prevents the tree from being dismounted when the type of root node is changed. This removes a lot of boilerplate when building applications. I think the file is rather unfortunately named though, so I reckon we should rename it.

- `require('nanomorph/loop')` (my preference)
- `require('nanomorph/update')`

thoughts? cc/ @kristoferjoseph

**Comment by kristoferjoseph** [comment]
Either works for me... 
"loop" does make me think "run loop" though.

**Comment by yoshuawuyts** [comment]
update it is then (:
