### ISSUE TITLE
Swap out using childNode for firstChild and nexSibling

### ISSUE THREAD

**Issue by kristoferjoseph** [yoshuawuyts/nanomorph#29]
See issue #25

**Comment by kristoferjoseph** [comment]
I investigated this and it is not an issue nanomorph has.

**Comment by yoshuawuyts** [comment]
@kristoferjoseph ohey, interesting - do you mean this does not speed up iterating things? How'd you measure that?

**Comment by kristoferjoseph** [comment]
@yoshuawuyts in a node env `firstChild` is not exposed on the element returned from `bel` so this is a non-starter.

**Comment by yoshuawuyts** [comment]
@kristoferjoseph ah yeah, fair enough :sparkles: - agree we should just go with whatever's available to us and not complicate things by going down different paths or whatever; unless it's a huge improvement but with caching I doubt it will matter too much

**Comment by kristoferjoseph** [comment]
@yoshuawuyts right. It started to look like we would need a branching strategy based on environment which felt wrong.
There is however a `firstChildElement` property that may give us what we want, but I have not looked into it much.

I feel you are correct in your idea that aggressive caching and early returning will be where most of the performance increases will come from. As it is this lib is smoking... hoping that fixing all the edge cases doesn't slow it down too much.

With that said, we could possibly consider using an immutable structure for quick comparisons of elements in a tree. _again caching_

**Comment by kristoferjoseph** [comment]
@yoshuawuyts check this idea out: 
https://github.com/kristoferjoseph/first-child-shim/blob/master/index.js
https://github.com/kristoferjoseph/next-sibling-shim

am I crazy?

**Comment by yoshuawuyts** [comment]
Innnnnteresting - I wonder how this will perform. Gut feeling is telling me
we should wait on merging any of these optimizations at least until after
we've landed swapping sibling nodes as it might change the algo a bit +
gives us some time to bench this

**Comment by kristoferjoseph** [comment]
totally agree that this is a farther down the road optimization... BUT the approach is super interesting to me.
We can use this same approach for attributes possibly as well.
It allows us to have different handling in server or browser context but maintain the same interface.
This specific firstChild/nextSibling optimization seems to make a big difference in the browser during large operations. 

We will def need to add some benchmarks for these types of additions.
