### ISSUE TITLE
nanomorph mutates the new DOM node tree

### ISSUE THREAD

**Issue by reminyborg** [yoshuawuyts/nanomorph#33]
When using [appendChild](https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild) to add children from the new tree to the original it removes them from the original.
Should we add a warning about this in the docs?

ref morphdom writes:
```
NOTE: This module will modify both the original and target DOM node tree during the transformation. It is assumed that the target DOM node tree will be discarded after the original DOM node tree is morphed.
```

**Comment by yoshuawuyts** [comment]
Ah yeah that makes sense; think adding a note to the readme would be great ✨

**Comment by yoshuawuyts** [comment]
Fixed!
