### ISSUE TITLE
[bug] copyAttributeNS only works on DOM nodes created with min-document

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/nanomorph#38]
```js
  var newAttrs = newNode._attributes
  var oldAttrs = oldNode._attributes
  var mergedAttrs = xtend(newAttrs, oldAttrs)
```

The `_attributes` value only exists on DOM nodes created with `min-document` / `bel` which is fine  - but once we use `yo-yoify` or native DOM nodes this'll break down.

**Comment by yoshuawuyts** [comment]
`.attributes` should be available on DOM nodes in the browser, although it doesn't quite appear to be the same; it's a weird enumerable thing I think

**Comment by yoshuawuyts** [comment]
We might need to run both Node and browser tests for this one; possibly using https://github.com/juliangruber/tape-run. Not stoked about it, but yeah if implementations are different then we shouldn't risk it imo

**Comment by kristoferjoseph** [comment]
This hasn't been an issue for me because initial renders are made server-side.

A test case where this would break is creating a `xlink:href` dynamically in the browser.
I'll add that with the `tape-run` test.

**Comment by yoshuawuyts** [comment]
neato!
