### ISSUE TITLE
Updating input

### ISSUE THREAD

**Issue by nicknikolov** [yoshuawuyts/nanomorph#59]
Hi Yosh,

sometimes I want to do 
```js
var newInput = html`<input></input>`
newInput.value = 42
return newInput
```
rather than
```js
var newInput = html`<input value=${value}></input>`
return newInput
```
then diff this thing somewhere else

But since you have this if-chain here https://github.com/yoshuawuyts/nanomorph/blob/32635c37f4272e1e225398e76e540de314a7b701/lib/morph.js#L118

it never really updates my value as written in the first case because I added the property but the attribute doesn't exist (I think?) :(
The way morphdom handles this is it checks these things independently: https://github.com/patrick-steele-idem/morphdom/blob/43b808008bd39b571a1dd32d49811c7c22bd2021/src/specialElHandlers.js#L32

I don't know if this should be considered a bug but it would be nice if my first case would be possible to do as sometimes elements get large and it's visually nice to set some stuff from outside.

Does this make sense? 😁 Sorry for putting more things on your plate, would have just sent PR but you might have had your reasons for doing it like this.

__edit by yoshuawuyts__ syntax highlighting

**Comment by yoshuawuyts** [comment]
As per IRC: if there's a patch + tests for this I'm :+1: on adding

**Comment by nicknikolov** [comment]
I'll try working on it!

**Comment by yoshuawuyts** [comment]
ping @nicknikolov have you had time to look at this?
