### ISSUE TITLE
API: old vs new order

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/nanomorph#7]
Was there any particular reason to use the order `newTree, oldTree` in the API? Maybe I'm just used to morphdom/yo-yo but I would have expected `oldTree, newTree` since you're _morphing_ the _old tree_ to become the _new tree_, no?

**Comment by yoshuawuyts** [comment]
oh, I was thinking more of it in terms of "apply newtree to oldtree" - believe the DOM's `document.replaceChild(newEl, oldEl)` work quite in the same way. Does that make sense?
