### ISSUE TITLE
Another Alternative.

### ISSUE THREAD

**Issue by DylanPiercey** [yoshuawuyts/nanomorph#9]
@yoshuawuyts I have also tried to create this exact thing for use in a framework I have been building. It's located [here](https://github.com/DylanPiercey/set-dom), perhaps it could provide some inspiration since it is a slightly different approach and it also addresses node ordering with `data-key` and `id` attributes. It also supports namespaces in a pretty clean way.

Anyways this is a non issue but thought I would shoot this your way.
Feel free to close.

**Comment by yoshuawuyts** [comment]
Oh sweet! - that looks heaps nice, wasn't aware it existed. I'll def take a look. Heaps thanks for chiming in! :rocket:

**Comment by yoshuawuyts** [comment]
Added to docs in https://github.com/yoshuawuyts/nanomorph/commit/ecea21da4ea63ea7f7a2b85ab8c543828289e3c5

**Comment by DylanPiercey** [comment]
@yoshuawuyts - Sweet, thanks for adding it.
Hopefully it can be of some help.
